apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: keycloak
  namespace: keycloak-system
spec:
  chart:
    url: oci://ghcr.io/krateo-blueprints/charts/keycloak
    version: "0.1.0"
