apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ .Values.keycloak.name }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.keycloak.instances }}
  {{- with .Values.keycloak.image }}
  image: {{ . | quote }}
  {{- end }}
  db:
    vendor: {{ .Values.db.vendor }}
    database: {{ .Values.db.database }}
    {{- if eq .Values.db.provider "cloudnativepg" }}
    host: {{ .Values.db.cloudnativepg.clusterName }}-rw
    port: 5432
    usernameSecret:
      name: {{ .Values.db.cloudnativepg.clusterName }}-app
      key: username
    passwordSecret:
      name: {{ .Values.db.cloudnativepg.clusterName }}-app
      key: password
    {{- else }}
    host: {{ .Values.db.host }}
    port: {{ .Values.db.port }}
    usernameSecret:
      name: {{ .Values.db.secret.name }}
      key: {{ .Values.db.secret.usernameKey }}
    passwordSecret:
      name: {{ .Values.db.secret.name }}
      key: {{ .Values.db.secret.passwordKey }}
    {{- end }}
  http:
    httpEnabled: {{ .Values.keycloak.http.httpEnabled }}
    {{- with .Values.keycloak.http.tlsSecretName }}
    tlsSecret: {{ . | quote }}
    {{- end }}
  hostname:
    hostname: {{ .Values.keycloak.hostname | quote }}
  ingress:
    enabled: {{ .Values.keycloak.ingress.enabled }}
    {{- with .Values.keycloak.ingress.className }}
    className: {{ . | quote }}
    {{- end }}
  {{- with .Values.keycloak.proxyHeaders }}
  proxy:
    headers: {{ . | quote }}
  {{- end }}
  {{- if .Values.bootstrapAdmin.enabled }}
  bootstrapAdmin:
    user:
      secret: {{ .Values.bootstrapAdmin.secret.name }}
  {{- end }}
  {{- with .Values.keycloak.additionalOptions }}
  additionalOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
